ALTER TABLE todos ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE todos ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

UPDATE todos SET created_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP;

ALTER TABLE todos ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE todos ALTER COLUMN updated_at SET NOT NULL;