name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  pull_request:
    type: ["opened"]
    branches:
      - main

  push:
    branches:
      - main
jobs:
  # CI run
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js 24
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: "npm" # Automatically caches your npm dependencies
      - run: npm ci # installs all the dependencies
      - run: npm run lint
      - run: npm run typecheck
      - run: npm test
      # We wanna build only when we have passed all checks
      - run: npm run build
